### PR TITLE
Feature/vultr lb

### PR DESCRIPTION
**Pull request by jstoja**
##### SUMMARY

Implement Vultr Load Balancer API (https://www.vultr.com/api/#loadbalancer)

From https://github.com/ansible-collections/community.general/pull/159

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
vulr_lb

##### ADDITIONAL INFORMATION

Goal is something like this:

```
- vultr_lb:
    dcid: 1
    algorithm: Leastconn
    label: web
    state: present
    forwarding_rules:
      - frontend_protocol: https
        frontend_port: 81
        backend_protocol: https
        backend_port: 81
```

### CODE REVIEW

**Comment by resmo** [comment]
Thanks for your contribution, let me know if I can help to get the santiy CI through. There is an issue with the later tests "integration test using python ..." currently don't expect this to succeed.

**Comment by jstoja** [comment]
I saw that I can still improve the documentation as the `type` field isn't correct. I should explicit those fields with `suboptions` from what I could find in the ansible documentation.

**Comment by resmo** [comment]
yes, see https://github.com/ansible-collections/azure/blob/dev/plugins/modules/azure_rm_securitygroup.py#L619 as example

**Comment by jstoja** [comment]
@resmo It seems that the integrations tests are failing but aren't linked to my changes:
```
Running vultr_account_info integration test role
ERROR: No section: 'default'
ERROR: The 1 integration test(s) listed below (out of 1) failed. See error output above for details:
vultr_account_info
```

Can you confirm?

**Comment by resmo** [comment]
yes, I confirm.

**Comment by resmo** [comment]
Thank you very much for your contribution.

In the meantime, Vultr has deprecated the v1 API and we have been working with @vultr to re-implement the modules with the v2 API.  

Therefore, this collection is now in maintenance mode and we encourage you to contribute new feature now here https://github.com/vultr/ansible-collection-vultr/.

**Pull request closed without merging**
